const views=[...document.querySelectorAll('.view')];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function show(id){views.forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='admin')checkAdmin();if(id==='student')checkStudent();}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
async function api(url,opt={}){try{const r=await fetch(url,{credentials:'same-origin',...opt});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`خطا ${r.status}`);return data}catch(e){if(e instanceof TypeError)throw new Error('اتصال به سرور برقرار نشد. سایت باید روی سرور اجرا شده باشد.');throw e}}
function msg(el,text,error=false){el.textContent=text;el.className=error?'message error':'message ok'}
async function checkAdmin(){try{const me=await api('/api/me');if(me.role==='ADMIN')openAdmin(me)}catch{}}
async function checkStudent(){try{const me=await api('/api/me');if(me.role==='STUDENT')openStudent(me)}catch{}}
function openAdmin(me){$('adminLoginBox').classList.add('hidden');$('adminArea').classList.remove('hidden');loadAdmin()}
function openStudent(me){$('studentLoginBox').classList.add('hidden');$('studentArea').classList.remove('hidden');$('studentWelcome').textContent=`سلام ${me.name} عزیز!`;loadStudent()}
$('adminLogin').addEventListener('click',async()=>{const b=$('adminLogin');b.disabled=true;try{const d=await api('/api/auth/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('adminUser').value.trim(),password:$('adminPass').value})});openAdmin(d.user)}catch(e){msg($('adminMsg'),e.message,true)}finally{b.disabled=false}});
$('requestOtp').addEventListener('click',async()=>{const b=$('requestOtp');b.disabled=true;try{const d=await api('/api/auth/student/request-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:$('studentPhone').value.trim()})});$('otpBox').classList.remove('hidden');$('studentMsg').textContent=d.devCode?`کد ورود آزمایشی: ${d.devCode}`:'کد ورود ارسال شد.'}catch(e){$('studentMsg').textContent=e.message}finally{b.disabled=false}});
$('verifyOtp').addEventListener('click',async()=>{const b=$('verifyOtp');b.disabled=true;try{const d=await api('/api/auth/student/verify-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:$('studentPhone').value.trim(),code:$('studentOtp').value.trim()})});openStudent(d.user)}catch(e){$('studentMsg').textContent=e.message}finally{b.disabled=false}});
document.querySelectorAll('.logoutBtn').forEach(b=>b.addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()}));
async function loadAdmin(){try{const [students,courses]=await Promise.all([api('/api/admin/students'),api('/api/admin/courses')]);window.adminData={students,courses};renderAdmin()}catch(e){msg($('adminMsg'),e.message,true)}}
function renderAdmin(){const {students,courses}=window.adminData;$('studentCount').textContent=students.length;$('courseCount').textContent=courses.length;$('studentList').innerHTML=students.map(s=>`<div class="student-row"><span><b>${esc(s.name)}</b><br><small>${esc(s.mobile)}</small></span><button class="secondary" onclick="deleteStudent('${s.id}')">حذف</button></div>`).join('')||'<p style="color:#6b7890">هنوز دانش‌آموزی ثبت نشده است.</p>';$('courseList').innerHTML=courses.map(c=>`<div class="course-admin"><b>${esc(c.title)}</b><br><small>${esc(c.level||'')}</small><button class="secondary" onclick="deleteCourse('${c.id}')">حذف دوره</button></div>`).join('')||'<p style="color:#6b7890">هنوز دوره‌ای ساخته نشده است.</p>';$('enrollStudent').innerHTML=students.map(s=>`<option value="${s.id}">${esc(s.name)} — ${esc(s.mobile)}</option>`).join('');$('enrollCourse').innerHTML=courses.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('');$('courseTree').innerHTML=courses.map(renderCourseAdmin).join('')||'<p style="color:#6b7890">اول یک دوره بساز.</p>'}
window.deleteStudent=async id=>{if(!confirm('این دانش‌آموز حذف شود؟'))return;try{await api('/api/admin/students/'+id,{method:'DELETE'});loadAdmin()}catch(e){alert(e.message)}};
window.deleteCourse=async id=>{if(!confirm('این دوره و همه درس‌ها و ویدئوهایش حذف شود؟'))return;try{await api('/api/admin/courses/'+id,{method:'DELETE'});loadAdmin()}catch(e){alert(e.message)}};
window.deleteLesson=async id=>{if(!confirm('این درس حذف شود؟'))return;try{await api('/api/admin/lessons/'+id,{method:'DELETE'});loadAdmin()}catch(e){alert(e.message)}};
window.deleteSection=async id=>{if(!confirm('این بخش و ویدئوی آن حذف شود؟'))return;try{await api('/api/admin/sections/'+id,{method:'DELETE'});loadAdmin()}catch(e){alert(e.message)}};
function renderCourseAdmin(c){return `<div class="course-admin"><b>📘 ${esc(c.title)}</b><span> — ${esc(c.level||'')}</span><div class="mini-form"><input id="lesson-${c.id}" placeholder="نام درس جدید"><button class="secondary" onclick="addLesson('${c.id}')">+ درس</button></div>${c.lessons.map(l=>`<div class="lesson-admin"><b>📖 ${esc(l.title)}</b> <button class="secondary" onclick="deleteLesson('${l.id}')">حذف درس</button><div class="mini-form"><input id="section-${l.id}" placeholder="نام بخش جدید"><button class="secondary" onclick="addSection('${l.id}')">+ بخش</button></div>${l.sections.map(s=>`<div class="section-admin"><span>${s.videoPath?'🎥':'▫️'} ${esc(s.title)}</span><span>${s.videoPath?'ویدئو دارد':'بدون ویدئو'} <label class="secondary" style="padding:6px 9px;display:inline-block;cursor:pointer"><input type="file" accept="video/*" style="display:none" onchange="uploadVideo('${s.id}',this)">آپلود / جایگزینی</label> <button class="secondary" onclick="deleteSection('${s.id}')">حذف</button></span></div>`).join('')}</div>`).join('')}</div>`}
window.addLesson=async cid=>{const v=$('lesson-'+cid).value.trim();if(!v)return;try{await api(`/api/admin/courses/${cid}/lessons`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:v})});loadAdmin()}catch(e){alert(e.message)}};
window.addSection=async lid=>{const v=$('section-'+lid).value.trim();if(!v)return;try{await api(`/api/admin/lessons/${lid}/sections`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:v})});loadAdmin()}catch(e){alert(e.message)}};
window.uploadVideo=async(sid,input)=>{const file=input.files?.[0];if(!file)return;if(!file.type.startsWith('video/')){alert('لطفاً یک فایل ویدئویی انتخاب کن.');return}const f=new FormData();f.append('video',file);input.disabled=true;try{await api(`/api/admin/sections/${sid}/video`,{method:'POST',body:f});alert('ویدئو با موفقیت روی سرور ذخیره شد.');loadAdmin()}catch(e){alert(e.message)}finally{input.disabled=false}};
$('addStudent').addEventListener('click',async()=>{try{await api('/api/admin/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('newName').value.trim(),mobile:$('newPhone').value.trim()})});$('newName').value='';$('newPhone').value='';loadAdmin()}catch(e){alert(e.message)}});
$('addCourse').addEventListener('click',async()=>{try{await api('/api/admin/courses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('newCourseTitle').value.trim(),level:$('newCourseLevel').value.trim(),description:$('newCourseDesc').value.trim()})});$('newCourseTitle').value='';$('newCourseLevel').value='';$('newCourseDesc').value='';loadAdmin()}catch(e){alert(e.message)}});
$('saveEnrollment').addEventListener('click',async()=>{try{await api('/api/admin/enrollments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId:$('enrollStudent').value,courseId:$('enrollCourse').value,status:$('enrollStatus').value})});msg($('enrollmentMsg'),'دسترسی دانش‌آموز ذخیره شد.')}catch(e){msg($('enrollmentMsg'),e.message,true)}});
async function loadStudent(){try{const [courses,locked]=await Promise.all([api('/api/student/courses'),api('/api/student/locked')]);$('studentCourses').innerHTML=[...courses.map(c=>`<article class="course"><h3>🟢 ${esc(c.title)}</h3><p>${esc(c.description||'دوره آموزشی Journey to English')}</p>${c.lessons.map(l=>`<div class="lesson-admin"><b>📖 ${esc(l.title)}</b>${l.sections.map(s=>`<div class="section-admin"><span>${esc(s.title)}</span>${s.videoPath?`<button class="primary" onclick="playVideo('${s.id}',this)">▶ پخش</button>`:'<small>ویدئو هنوز اضافه نشده</small>'}</div>`).join('')}</div>`).join('')}</article>`),...locked.map(e=>`<article class="course"><h3>🔒 ${esc(e.course.title)}</h3><p>این دوره فعلاً برای شما قفل است.</p></article>`)];if(!courses.length&&!locked.length)$('studentCourses').innerHTML='<p>هنوز دوره‌ای برای شما فعال نشده است.</p>'}catch(e){$('studentCourses').innerHTML=`<div class="message error">${esc(e.message)}</div>`}}
window.playVideo=async(id,button)=>{try{const d=await api('/api/student/sections/'+id+'/video-url');let old=document.getElementById('video-'+id);if(old)old.remove();const v=document.createElement('video');v.id='video-'+id;v.controls=true;v.controlsList='nodownload';v.disablePictureInPicture=true;v.playsInline=true;v.preload='metadata';v.style='width:100%;margin-top:10px;border-radius:14px;background:#000';v.src=d.url;button.parentElement.parentElement.appendChild(v);v.play().catch(()=>{})}catch(e){alert(e.message)}};
